### ISSUE TITLE
Pending providers are missing an identifier

### ISSUE THREAD

**Issue by benbender** [kiebitz-oss/vanellus#16]
Providers which aren't confirmed yet doesn't seem to have an unique identifier. The absence of an unique ID makes it hard to be referenced in the UI. An ID seem to be assigned after confirmation (see PublicProviderData-interface).

**Comment by adewes** [comment]
Seems the ID field was not annotated, it is present in the data though.

**Comment by benbender** [comment]
From what I see, I'm getting the `.id`-field on EncryptedProviderData (using verifiedProviders()) itself and not on `encryptedProviderData.data.id`. It would be nice though to have a stable `id` starting with the creation of a pending provider inside the ProviderData-Interface.

**Comment by tauli** [comment]
Seems to me like the id that's used to identify the provider for most things on the backend is just a SHA256 hash of the signing public key. That should be both unique and permanent. imho this should be easy to include into the ProviderData interface. What do you think?
